// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  campfireId: __t.u64().primaryKey().name("campfire_id"),
  ownerId: __t.identity().name("owner_id"),
  ownerName: __t.string().name("owner_name"),
  x: __t.f32(),
  y: __t.f32(),
  litAt: __t.u64().name("lit_at"),
  expiresAt: __t.u64().name("expires_at"),
});
