// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  mobId: __t.u64().primaryKey().name("mob_id"),
  mobType: __t.string().name("mob_type"),
  x: __t.f32(),
  y: __t.f32(),
  hp: __t.i32(),
  maxHp: __t.i32().name("max_hp"),
  state: __t.string(),
  spawnNetId: __t.string().name("spawn_net_id"),
  spawnX: __t.f32().name("spawn_x"),
  spawnY: __t.f32().name("spawn_y"),
  aggroRadiusPx: __t.f32().name("aggro_radius_px"),
  leashRadiusPx: __t.f32().name("leash_radius_px"),
  respawnSec: __t.u32().name("respawn_sec"),
  lastAttackAt: __t.u64().name("last_attack_at"),
});
