// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  identity: __t.identity().primaryKey(),
  username: __t.string(),
  classType: __t.string().name("class_type"),
  avatarColor: __t.string().name("avatar_color"),
  x: __t.f32(),
  y: __t.f32(),
  direction: __t.u8(),
  isMoving: __t.bool().name("is_moving"),
  zoneId: __t.u8().name("zone_id"),
  online: __t.bool(),
  avatarConfig: __t.string().name("avatar_config"),
  lastChatAt: __t.u64().name("last_chat_at"),
  lastAttackAt: __t.u64().name("last_attack_at"),
});
