// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.u64(),
  senderId: __t.identity(),
  senderName: __t.string(),
  text: __t.string(),
  sentAt: __t.u64(),
  msgType: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  username: __t.string(),
  classType: __t.string(),
  avatarColor: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  direction: __t.u8(),
  isMoving: __t.bool(),
  zoneId: __t.u8(),
  online: __t.bool(),
});
export type Player = __Infer<typeof Player>;

