// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.u64(),
  senderId: __t.identity(),
  senderName: __t.string(),
  text: __t.string(),
  sentAt: __t.u64(),
  msgType: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const Mob = __t.object("Mob", {
  mobId: __t.u64(),
  mobType: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  hp: __t.i32(),
  maxHp: __t.i32(),
  state: __t.string(),
  spawnNetId: __t.string(),
  spawnX: __t.f32(),
  spawnY: __t.f32(),
  aggroRadiusPx: __t.f32(),
  leashRadiusPx: __t.f32(),
  respawnSec: __t.u32(),
  lastAttackAt: __t.u64(),
});
export type Mob = __Infer<typeof Mob>;

export const MobAiTickScheduleRow = __t.object("MobAiTickScheduleRow", {
  id: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type MobAiTickScheduleRow = __Infer<typeof MobAiTickScheduleRow>;

export const MobRespawnQueueRow = __t.object("MobRespawnQueueRow", {
  id: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  spawnNetId: __t.string(),
});
export type MobRespawnQueueRow = __Infer<typeof MobRespawnQueueRow>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  username: __t.string(),
  classType: __t.string(),
  avatarColor: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  direction: __t.u8(),
  isMoving: __t.bool(),
  zoneId: __t.u8(),
  online: __t.bool(),
  avatarConfig: __t.string(),
  lastChatAt: __t.u64(),
  lastAttackAt: __t.u64(),
  hp: __t.i32(),
  maxHp: __t.i32(),
  deadUntil: __t.u64(),
});
export type Player = __Infer<typeof Player>;

export const PlayerRespawnQueueRow = __t.object("PlayerRespawnQueueRow", {
  id: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  identity: __t.identity(),
});
export type PlayerRespawnQueueRow = __Infer<typeof PlayerRespawnQueueRow>;

