// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Campfire = __t.object("Campfire", {
  campfireId: __t.u64(),
  ownerId: __t.identity(),
  ownerName: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  litAt: __t.u64(),
  expiresAt: __t.u64(),
});
export type Campfire = __Infer<typeof Campfire>;

export const CampfireExpireQueueRow = __t.object("CampfireExpireQueueRow", {
  id: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  campfireId: __t.u64(),
});
export type CampfireExpireQueueRow = __Infer<typeof CampfireExpireQueueRow>;

export const ChatMessage = __t.object("ChatMessage", {
  id: __t.u64(),
  senderId: __t.identity(),
  senderName: __t.string(),
  text: __t.string(),
  sentAt: __t.u64(),
  msgType: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
});
export type ChatMessage = __Infer<typeof ChatMessage>;

export const DungeonInstance = __t.object("DungeonInstance", {
  instanceId: __t.u64(),
  dungeonId: __t.string(),
  createdAt: __t.u64(),
});
export type DungeonInstance = __Infer<typeof DungeonInstance>;

export const Mob = __t.object("Mob", {
  mobId: __t.u64(),
  mobType: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  hp: __t.i32(),
  maxHp: __t.i32(),
  state: __t.string(),
  spawnNetId: __t.string(),
  spawnX: __t.f32(),
  spawnY: __t.f32(),
  aggroRadiusPx: __t.f32(),
  leashRadiusPx: __t.f32(),
  respawnSec: __t.u32(),
  lastAttackAt: __t.u64(),
  dungeonInstanceId: __t.u64(),
  floorYm: __t.f32(),
  spawnedAt: __t.u64(),
  lastAoeAt: __t.u64(),
  enraged: __t.bool(),
});
export type Mob = __Infer<typeof Mob>;

export const MobAiTickScheduleRow = __t.object("MobAiTickScheduleRow", {
  id: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type MobAiTickScheduleRow = __Infer<typeof MobAiTickScheduleRow>;

export const MobRespawnQueueRow = __t.object("MobRespawnQueueRow", {
  id: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  spawnNetId: __t.string(),
  dungeonInstanceId: __t.u64(),
});
export type MobRespawnQueueRow = __Infer<typeof MobRespawnQueueRow>;

export const Player = __t.object("Player", {
  identity: __t.identity(),
  username: __t.string(),
  classType: __t.string(),
  avatarColor: __t.string(),
  x: __t.f32(),
  y: __t.f32(),
  direction: __t.u8(),
  isMoving: __t.bool(),
  zoneId: __t.u8(),
  online: __t.bool(),
  avatarConfig: __t.string(),
  lastChatAt: __t.u64(),
  lastAttackAt: __t.u64(),
  hp: __t.i32(),
  maxHp: __t.i32(),
  deadUntil: __t.u64(),
  dungeonInstanceId: __t.u64(),
  floorYm: __t.f32(),
  lastMoveAt: __t.u64(),
});
export type Player = __Infer<typeof Player>;

export const PlayerChestOpened = __t.object("PlayerChestOpened", {
  id: __t.u64(),
  owner: __t.identity(),
  chestId: __t.u32(),
});
export type PlayerChestOpened = __Infer<typeof PlayerChestOpened>;

export const PlayerEquipped = __t.object("PlayerEquipped", {
  id: __t.u64(),
  owner: __t.identity(),
  slot: __t.string(),
  itemId: __t.string(),
});
export type PlayerEquipped = __Infer<typeof PlayerEquipped>;

export const PlayerItemStack = __t.object("PlayerItemStack", {
  id: __t.u64(),
  owner: __t.identity(),
  itemId: __t.string(),
  quantity: __t.u32(),
});
export type PlayerItemStack = __Infer<typeof PlayerItemStack>;

export const PlayerProgress = __t.object("PlayerProgress", {
  identity: __t.identity(),
  fitnessXp: __t.u64(),
  fitnessXpBaseline: __t.u64(),
  worldLevel: __t.u32(),
});
export type PlayerProgress = __Infer<typeof PlayerProgress>;

export const PlayerQuest = __t.object("PlayerQuest", {
  id: __t.u64(),
  owner: __t.identity(),
  questId: __t.string(),
  state: __t.u8(),
  countsJson: __t.string(),
  acceptedAt: __t.u64(),
});
export type PlayerQuest = __Infer<typeof PlayerQuest>;

export const PlayerRespawnQueueRow = __t.object("PlayerRespawnQueueRow", {
  id: __t.u64(),
  scheduledAt: __t.scheduleAt(),
  identity: __t.identity(),
});
export type PlayerRespawnQueueRow = __Infer<typeof PlayerRespawnQueueRow>;

export const PlayerWallet = __t.object("PlayerWallet", {
  identity: __t.identity(),
  copper: __t.u64(),
  imported: __t.bool(),
});
export type PlayerWallet = __Infer<typeof PlayerWallet>;

