/**
 * terrain_sync_state.mjs
 *
 * Pure state model for the terrain pipeline's offline freshness gate.
 * config/terrain-assets.lock.json records, at the time of the last successful
 * normalization build:
 *   - a digest of every image- or manifest-affecting field of
 *     config/terrain-assets.json (metadata-only edits, e.g. acquisition notes
 *     or disabled candidates, do not invalidate it);
 *   - the SHA-256 of public/assets/terrain/manifest.json;
 *   - the SHA-256 of every generated output file per enabled set.
 *
 * sync_terrain_assets.mjs verifies the committed outputs against the lock and
 * only rebuilds (from local sources) when something real changed. Nothing in
 * this module touches the network.
 */

import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import { resolve } from 'node:path';

export const LOCK_RELATIVE_PATH = 'config/terrain-assets.lock.json';

function sortKeysDeep(value) {
  if (Array.isArray(value)) return value.map(sortKeysDeep);
  if (value && typeof value === 'object') {
    const sorted = {};
    for (const key of Object.keys(value).sort()) sorted[key] = sortKeysDeep(value[key]);
    return sorted;
  }
  return value;
}

export function canonicalJson(value) {
  return JSON.stringify(sortKeysDeep(value));
}

function sha256Hex(bytes) {
  return createHash('sha256').update(bytes).digest('hex');
}

export async function hashFile(path) {
  return sha256Hex(await readFile(path));
}

async function tryHashFile(path) {
  try {
    return await hashFile(path);
  } catch {
    return null;
  }
}

/**
 * The subset of the config that determines generated bytes and manifest
 * content. Per-set knobs are resolved through defaults so that a defaults
 * change only invalidates the sets that actually inherit it.
 */
export function digestRelevantConfig(config) {
  const defaults = config.defaults ?? {};
  const sets = {};
  for (const [id, def] of Object.entries(config.sets ?? {})) {
    if (!def || def.enabled === false) continue;
    sets[id] = {
      role: def.role ?? null,
      resolution: def.resolution ?? defaults.resolution,
      tileMeters: def.tileMeters ?? defaults.tileMeters,
      anisotropy: def.anisotropy ?? defaults.anisotropy,
      baseColorQuality: def.baseColorQuality ?? defaults.baseColorQuality,
      roughness: def.roughness ?? defaults.roughness,
      maps: def.maps ?? null,
      license: def.license ?? null,
      download: def.acquisition?.download ?? null,
    };
  }
  return {
    version: config.version ?? null,
    output: config.output ?? null,
    profiles: config.profiles ?? null,
    sets,
  };
}

export function computeConfigDigest(config) {
  return sha256Hex(canonicalJson(digestRelevantConfig(config)));
}

/** Runtime-contract filenames each enabled set must provide (see build_terrain_assets.mjs). */
export function expectedOutputFiles(config) {
  const files = {};
  for (const [id, def] of Object.entries(config.sets ?? {})) {
    if (!def || def.enabled === false) continue;
    files[id] = ['basecolor.jpg', 'normal.png', 'orm.png', ...(def.maps?.height ? ['height.png'] : [])];
  }
  return files;
}

/** Snapshot the on-disk outputs into a lock object. Throws if an output is missing. */
export async function buildLock({ repoRoot, config }) {
  const manifestSha256 = await hashFile(resolve(repoRoot, config.output.manifest));
  const sets = {};
  for (const [id, names] of Object.entries(expectedOutputFiles(config))) {
    const files = {};
    for (const name of names) {
      files[name] = await hashFile(resolve(repoRoot, config.output.directory, id, name));
    }
    sets[id] = { files };
  }
  return {
    version: 1,
    configDigest: computeConfigDigest(config),
    manifestSha256,
    sets,
  };
}

/** Compare config + on-disk outputs against the lock. Never touches the network. */
export async function verifyTerrainState({ repoRoot, config, lock }) {
  if (!lock || typeof lock !== 'object') {
    return { current: false, reasons: [`${LOCK_RELATIVE_PATH} (terrain lockfile) is missing`] };
  }

  const reasons = [];
  if (lock.version !== 1) reasons.push(`unsupported lock version: ${lock.version}`);
  if (lock.configDigest !== computeConfigDigest(config)) {
    reasons.push('config/terrain-assets.json changed since the outputs were last built');
  }

  const manifestHash = await tryHashFile(resolve(repoRoot, config.output.manifest));
  if (manifestHash === null) {
    reasons.push(`runtime manifest is missing: ${config.output.manifest}`);
  } else if (manifestHash !== lock.manifestSha256) {
    reasons.push(`runtime manifest does not match the lock: ${config.output.manifest}`);
  }

  for (const [id, names] of Object.entries(expectedOutputFiles(config))) {
    const locked = lock.sets?.[id]?.files;
    if (!locked || typeof locked !== 'object') {
      reasons.push(`lock has no entry for enabled set "${id}"`);
      continue;
    }
    for (const name of new Set([...names, ...Object.keys(locked)])) {
      if (!names.includes(name)) {
        reasons.push(`lock lists an unexpected file for ${id}: ${name}`);
        continue;
      }
      if (typeof locked[name] !== 'string') {
        reasons.push(`lock is missing a hash for ${id}/${name}`);
        continue;
      }
      const actual = await tryHashFile(resolve(repoRoot, config.output.directory, id, name));
      if (actual === null) {
        reasons.push(`generated output is missing: ${id}/${name}`);
      } else if (actual !== locked[name]) {
        reasons.push(`generated output does not match the lock: ${id}/${name}`);
      }
    }
  }

  return { current: reasons.length === 0, reasons };
}
