// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import MovePlayerReducer from "../move_player_reducer";
import SendChatReducer from "../send_chat_reducer";
import SetPlayerInfoReducer from "../set_player_info_reducer";

export type MovePlayerParams = __Infer<typeof MovePlayerReducer>;
export type SendChatParams = __Infer<typeof SendChatReducer>;
export type SetPlayerInfoParams = __Infer<typeof SetPlayerInfoReducer>;

